export declare const OP_GET = 0;
export declare const OP_SET = 1;
export declare const OP_ADD = 2;
export declare const OP_REPLACE = 3;
export declare const OP_DELETE = 4;
export declare const OP_INCREMENT = 5;
export declare const OP_DECREMENT = 6;
export declare const OP_QUIT = 7;
export declare const OP_FLUSH = 8;
export declare const OP_GETQ = 9;
export declare const OP_NO_OP = 10;
export declare const OP_VERSION = 11;
export declare const OP_GETK = 12;
export declare const OP_GETKQ = 13;
export declare const OP_APPEND = 14;
export declare const OP_PREPEND = 15;
export declare const OP_STAT = 16;
export declare const OP_SETQ = 17;
export declare const OP_ADDQ = 18;
export declare const OP_REPLACEQ = 19;
export declare const OP_DELETEQ = 20;
export declare const OP_INCREMENTQ = 21;
export declare const OP_DECREMENTQ = 22;
export declare const OP_QUITQ = 23;
export declare const OP_FLUSHQ = 24;
export declare const OP_APPENDQ = 25;
export declare const OP_PREPENDQ = 26;
export declare const OP_VERBOSITY = 27;
export declare const OP_TOUCH = 28;
export declare const OP_GAT = 29;
export declare const OP_GATQ = 30;
export declare const OP_HELO = 31;
export declare const OP_SASL_LIST_MECHS = 32;
export declare const OP_SASL_AUTH = 33;
export declare const OP_SASL_STEP = 34;
export declare const OP_IOCTL_GET = 35;
export declare const OP_IOCTL_SET = 36;
export declare const OP_CONFIG_VALIDATE = 37;
export declare const OP_CONFIG_RELOAD = 38;
export declare const OP_AUDIT_PUT = 39;
export declare const OP_AUDIT_CONFIG_RELOAD = 40;
export declare const OP_SHUTDOWN = 41;
export declare const OP_RGET = 48;
export declare const OP_RSET = 49;
export declare const OP_RSETQ = 50;
export declare const OP_RAPPEND = 51;
export declare const OP_RAPPENDQ = 52;
export declare const OP_RPREPEND = 53;
export declare const OP_RPREPENDQ = 54;
export declare const OP_RDELETE = 55;
export declare const OP_RDELETEQ = 56;
export declare const OP_RINCR = 57;
export declare const OP_RINCRQ = 58;
export declare const OP_RDECR = 59;
export declare const OP_RDECRQ = 60;
export declare const OP_SET_VBUCKET = 61;
export declare const OP_GET_VBUCKET = 62;
export declare const OP_DEL_VBUCKET = 63;
export declare const OP_TAP_CONNECT = 64;
export declare const OP_TAP_MUTATION = 65;
export declare const OP_TAP_DELETE = 66;
export declare const OP_TAP_FLUSH = 67;
export declare const OP_TAP_OPAQUE = 68;
export declare const OP_TAP_VBUCKET_SET = 69;
export declare const OP_TAP_CHECKOUT_START = 70;
export declare const OP_TAP_CHECKPOINT_END = 71;
export declare const OP_GET_ALL_VB_SEQNOS = 72;
export declare const OP_DCP_OPEN = 80;
export declare const OP_DCP_ADD_STREAM = 81;
export declare const OP_DCP_CLOSE_STREAM = 82;
export declare const OP_DCP_STREAM_REQ = 83;
export declare const OP_DCP_GET_FAILOVER_LOG = 84;
export declare const OP_DCP_STREAM_END = 85;
export declare const OP_DCP_SNAPSHOT_MARKER = 86;
export declare const OP_DCP_MUTATION = 87;
export declare const OP_DCP_DELETION = 88;
export declare const OP_DCP_EXPIRATION = 89;
export declare const OP_DCP_FLUSH = 90;
export declare const OP_DCP_SET_VBUCKET_STATE = 91;
export declare const OP_DCP_NOOP = 92;
export declare const OP_DCP_BUFFER_ACKNOWLEDGEMENT = 93;
export declare const OP_DCP_CONTROL = 94;
export declare const OP_DCP_RESERVED4 = 95;
export declare const OP_STOP_PERSISTENCE = 128;
export declare const OP_START_PERSISTENCE = 129;
export declare const OP_SET_PARAM = 130;
export declare const OP_GET_REPLICA = 131;
export declare const OP_CREATE_BUCKET = 133;
export declare const OP_DELETE_BUCKET = 134;
export declare const OP_LIST_BUCKETS = 135;
export declare const OP_SELECT_BUCKET = 137;
export declare const OP_ASSUME_ROLE = 138;
export declare const OP_OBSERVE_SEQNO = 145;
export declare const OP_OBSERVE = 146;
export declare const OP_EVICT_KEY = 147;
export declare const OP_GET_LOCKED = 148;
export declare const OP_UNLOCK_KEY = 149;
export declare const OP_LAST_CLOSED_CHECKPOINT = 151;
export declare const OP_DEREGISTER_TAP_CLIENT = 158;
export declare const OP_RESET_REPLICATION_CHAIN = 159;
export declare const OP_GET_META = 160;
export declare const OP_GETQ_META = 161;
export declare const OP_SET_WITH_META = 162;
export declare const OP_SETQ_WITH_META = 163;
export declare const OP_ADD_WITH_META = 164;
export declare const OP_ADDQ_WITH_META = 165;
export declare const OP_SNAPSHOT_VB_STATES = 166;
export declare const OP_VBUCKET_BATCH_COUNT = 167;
export declare const OP_DEL_WITH_META = 168;
export declare const OP_DELQ_WITH_META = 169;
export declare const OP_CREATE_CHECKPOINT = 170;
export declare const OP_NOTIFY_VBUCKET_UPDATE = 172;
export declare const OP_ENABLE_TRAFFIC = 173;
export declare const OP_DISABLE_TRAFFIC = 174;
export declare const OP_CHANGE_VB_FILTER = 176;
export declare const OP_CHECKPOINT_PERSISTENCE = 177;
export declare const OP_RETURN_META = 178;
export declare const OP_COMPACT_DB = 179;
export declare const OP_SET_CLUSTER_CONFIG = 180;
export declare const OP_GET_CLUSTER_CONFIG = 181;
export declare const OP_GET_RANDOM_KEY = 182;
export declare const OP_SEQNO_PERSISTENCE = 183;
export declare const OP_GET_KEYS = 184;
export declare const OP_SET_DRIFT_COUNTER_STATE = 193;
export declare const OP_GET_ADJUSTED_TIME = 194;
export declare const OP_SUBDOC_GET = 197;
export declare const OP_SUBDOC_EXISTS = 198;
export declare const OP_SUBDOC_DICT_ADD = 199;
export declare const OP_SUBDOC_DICT_UPSERT = 200;
export declare const OP_SUBDOC_DELETE = 201;
export declare const OP_SUBDOC_REPLACE = 202;
export declare const OP_SUBDOC_ARRAY_PUSH_LAST = 203;
export declare const OP_SUBDOC_ARRAY_PUSH_FIRST = 204;
export declare const OP_SUBDOC_ARRAY_INSERT = 205;
export declare const OP_SUBDOC_ARRAY_ADD_UNIQUE = 206;
export declare const OP_SUBDOC_COUNTER = 207;
export declare const OP_SUBDOC_MULTI_LOOKUP = 208;
export declare const OP_SUBDOC_MULTI_MUTATION = 209;
export declare const OP_SUBDOC_GET_COUNT = 210;
export declare const OP_SCRUB = 240;
export declare const OP_ISASL_REFRESH = 241;
export declare const OP_SSL_CERTS_REFRESH = 242;
export declare const OP_GET_CMD_TIMER = 243;
export declare const OP_SET_CTRL_TOKEN = 244;
export declare const OP_GET_CTRL_TOKEN = 245;
export declare const OP_INIT_COMPLETE = 246;
export declare type OP = typeof OP_GET | typeof OP_SET | typeof OP_ADD | typeof OP_REPLACE | typeof OP_DELETE | typeof OP_INCREMENT | typeof OP_DECREMENT | typeof OP_QUIT | typeof OP_FLUSH | typeof OP_GETQ | typeof OP_NO_OP | typeof OP_VERSION | typeof OP_GETK | typeof OP_GETKQ | typeof OP_APPEND | typeof OP_PREPEND | typeof OP_STAT | typeof OP_SETQ | typeof OP_ADDQ | typeof OP_REPLACEQ | typeof OP_DELETEQ | typeof OP_INCREMENTQ | typeof OP_DECREMENTQ | typeof OP_QUITQ | typeof OP_FLUSHQ | typeof OP_APPENDQ | typeof OP_PREPENDQ | typeof OP_VERBOSITY | typeof OP_TOUCH | typeof OP_GAT | typeof OP_GATQ | typeof OP_HELO | typeof OP_SASL_LIST_MECHS | typeof OP_SASL_AUTH | typeof OP_SASL_STEP | typeof OP_IOCTL_GET | typeof OP_IOCTL_SET | typeof OP_CONFIG_VALIDATE | typeof OP_CONFIG_RELOAD | typeof OP_AUDIT_PUT | typeof OP_AUDIT_CONFIG_RELOAD | typeof OP_SHUTDOWN | typeof OP_RGET | typeof OP_RSET | typeof OP_RSETQ | typeof OP_RAPPEND | typeof OP_RAPPENDQ | typeof OP_RPREPEND | typeof OP_RPREPENDQ | typeof OP_RDELETE | typeof OP_RDELETEQ | typeof OP_RINCR | typeof OP_RINCRQ | typeof OP_RDECR | typeof OP_RDECRQ | typeof OP_SET_VBUCKET | typeof OP_GET_VBUCKET | typeof OP_DEL_VBUCKET | typeof OP_TAP_CONNECT | typeof OP_TAP_MUTATION | typeof OP_TAP_DELETE | typeof OP_TAP_FLUSH | typeof OP_TAP_OPAQUE | typeof OP_TAP_VBUCKET_SET | typeof OP_TAP_CHECKOUT_START | typeof OP_TAP_CHECKPOINT_END | typeof OP_GET_ALL_VB_SEQNOS | typeof OP_DCP_OPEN | typeof OP_DCP_ADD_STREAM | typeof OP_DCP_CLOSE_STREAM | typeof OP_DCP_STREAM_REQ | typeof OP_DCP_GET_FAILOVER_LOG | typeof OP_DCP_STREAM_END | typeof OP_DCP_SNAPSHOT_MARKER | typeof OP_DCP_MUTATION | typeof OP_DCP_DELETION | typeof OP_DCP_EXPIRATION | typeof OP_DCP_FLUSH | typeof OP_DCP_SET_VBUCKET_STATE | typeof OP_DCP_NOOP | typeof OP_DCP_BUFFER_ACKNOWLEDGEMENT | typeof OP_DCP_CONTROL | typeof OP_DCP_RESERVED4 | typeof OP_STOP_PERSISTENCE | typeof OP_START_PERSISTENCE | typeof OP_SET_PARAM | typeof OP_GET_REPLICA | typeof OP_CREATE_BUCKET | typeof OP_DELETE_BUCKET | typeof OP_LIST_BUCKETS | typeof OP_SELECT_BUCKET | typeof OP_ASSUME_ROLE | typeof OP_OBSERVE_SEQNO | typeof OP_OBSERVE | typeof OP_EVICT_KEY | typeof OP_GET_LOCKED | typeof OP_UNLOCK_KEY | typeof OP_LAST_CLOSED_CHECKPOINT | typeof OP_DEREGISTER_TAP_CLIENT | typeof OP_RESET_REPLICATION_CHAIN | typeof OP_GET_META | typeof OP_GETQ_META | typeof OP_SET_WITH_META | typeof OP_SETQ_WITH_META | typeof OP_ADD_WITH_META | typeof OP_ADDQ_WITH_META | typeof OP_SNAPSHOT_VB_STATES | typeof OP_VBUCKET_BATCH_COUNT | typeof OP_DEL_WITH_META | typeof OP_DELQ_WITH_META | typeof OP_CREATE_CHECKPOINT | typeof OP_NOTIFY_VBUCKET_UPDATE | typeof OP_ENABLE_TRAFFIC | typeof OP_DISABLE_TRAFFIC | typeof OP_CHANGE_VB_FILTER | typeof OP_CHECKPOINT_PERSISTENCE | typeof OP_RETURN_META | typeof OP_COMPACT_DB | typeof OP_SET_CLUSTER_CONFIG | typeof OP_GET_CLUSTER_CONFIG | typeof OP_GET_RANDOM_KEY | typeof OP_SEQNO_PERSISTENCE | typeof OP_GET_KEYS | typeof OP_SET_DRIFT_COUNTER_STATE | typeof OP_GET_ADJUSTED_TIME | typeof OP_SUBDOC_GET | typeof OP_SUBDOC_EXISTS | typeof OP_SUBDOC_DICT_ADD | typeof OP_SUBDOC_DICT_UPSERT | typeof OP_SUBDOC_DELETE | typeof OP_SUBDOC_REPLACE | typeof OP_SUBDOC_ARRAY_PUSH_LAST | typeof OP_SUBDOC_ARRAY_PUSH_FIRST | typeof OP_SUBDOC_ARRAY_INSERT | typeof OP_SUBDOC_ARRAY_ADD_UNIQUE | typeof OP_SUBDOC_COUNTER | typeof OP_SUBDOC_MULTI_LOOKUP | typeof OP_SUBDOC_MULTI_MUTATION | typeof OP_SUBDOC_GET_COUNT | typeof OP_SCRUB | typeof OP_ISASL_REFRESH | typeof OP_SSL_CERTS_REFRESH | typeof OP_GET_CMD_TIMER | typeof OP_SET_CTRL_TOKEN | typeof OP_GET_CTRL_TOKEN | typeof OP_INIT_COMPLETE;
/**
 * Response statuses
 * https://github.com/memcached/memcached/wiki/BinaryProtocolRevamped#response-status
 */
export declare const ResponseStatus: {
    /** Named "No error" in the memcached docs, but clearer in code as "SUCCESS". */
    readonly SUCCESS: 0;
    readonly KEY_NOT_FOUND: 1;
    readonly KEY_EXISTS: 2;
    readonly VALUE_TOO_LARGE: 3;
    readonly INVALID_ARGUMENTS: 4;
    readonly ITEM_NOT_STORED: 5;
    readonly INCR_DECR_ON_NON_NUMERIC_VALUE: 6;
    readonly THE_VBUCKET_BELONGS_TO_ANOTHER_SERVER: 7;
    readonly AUTHENTICATION_ERROR: 8;
    readonly AUTHENTICATION_CONTINUE: 9;
    readonly UNKNOWN_COMMAND: 129;
    readonly OUT_OF_MEMORY: 130;
    readonly NOT_SUPPORTED: 131;
    readonly INTERNAL_ERROR: 132;
    readonly BUSY: 133;
    readonly TEMPORARY_FAILURE: 134;
};
export declare type ResponseStatus = typeof ResponseStatus[keyof typeof ResponseStatus];
export declare function responseStatusToString(responseStatus: ResponseStatus | undefined): string;
//# sourceMappingURL=constants.d.ts.map